### ISSUE TITLE
error when installing requierments

### ISSUE THREAD

**Issue by Houssembenmid** [nicolas-chaulet/torch-points3d#582] opened 2021-04-07 10:50 UTC
I tried to install the torch-points3d 
but it gives me a long error which behons with

 ERROR: Command errored out with exit status 1:
   command: 'C:\Users\49151\miniconda3\envs\torch\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\49151\\AppData\\Local\\Temp\\pip-install-xgp7o6rg\\torch-cluster_83e37f3c855c4034ac752ec89ca0cb4e\\setup.py'"'"'; __file__='"'"'C:\\Users\\49151\\AppData\\Local\\Temp\\pip-install-xgp7o6rg\\torch-cluster_83e37f3c855c4034ac752ec89ca0cb4e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\49151\AppData\Local\Temp\pip-wheel-808m_spo'
       cwd: C:\Users\49151\AppData\Local\Temp\pip-install-xgp7o6rg\torch-cluster_83e37f3c855c4034ac752ec89ca0cb4e\
  Complete output (11576 lines):
  running bdist_wheel
  running build
  running build_py
  creating build

has anyone experienced this issue please help

**Comment by nicolas-chaulet** [comment] 2021-04-07 13:04
Duplicate of #581

**Closed by nicolas-chaulet** 2021-04-07 13:04 UTC
