### ISSUE TITLE
Segfault during unittest: stPytorchClusterFPS

### ISSUE THREAD

**Issue by loicland** [nicolas-chaulet/torch-points3d#288] opened 2020-06-03 17:52 UTC
Hi,
after installing `poetry install --no-dev --no-root` sucecsfully and installing pycuda, I run the unittest but it ends with a segfault:
```
test_kpconv (test.test_api.TestAPIUnet) ... ok
test_pn2 (test.test_api.TestAPIUnet) ... ok
test_rsconv (test.test_api.TestAPIUnet) ... The down_conv_nn has a different size as radii. Make sure of have SharedRSConv
ok
test_get_sample (test.test_basedataset.TestBatchCollate) ... ok
test_num_batches (test.test_basedataset.TestBatchCollate) ... ok
test_empty_dataset (test.test_basedataset.TestDataset) ... ok
test_get_by_name (test.test_basedataset.TestDataset) ... ok
test_multiple_test_datasets (test.test_basedataset.TestDataset) ... ok
test_normal (test.test_basedataset.TestDataset) ... ok
test_simple_datasets (test.test_basedataset.TestDataset) ... ok
test_getinput (test.test_basemodel.TestBaseModel) ... ok
test_accumulated_gradient (test.test_basemodel.TestSimpleBatch) ... ok
test_enable_dropout_eval (test.test_basemodel.TestSimpleBatch) ... ok
test_fromlist (test.test_batch.TestSimpleBatch) ... ok
test_scheduler (test.test_bn_scheduler.TestBNMomentumScheduler) ... ok
test_getCount (test.test_confusionMatrix.TestConfusionMatrix) ... ok
test_getIoU (test.test_confusionMatrix.TestConfusionMatrix) ... ok
test_getIoUMissing (test.test_confusionMatrix.TestConfusionMatrix) ... ok
test_getMeanIoU (test.test_confusionMatrix.TestConfusionMatrix) ... ok
test_test_getMeanIoUMissing (test.test_confusionMatrix.TestConfusionMatrix) ... ok
test_simple (test.test_dataset_factory.TestBaseFactory) ... This should happen only during testing
ok
test_composition (test.test_filter.TestFilter) ... ok
test_planarity_filter (test.test_filter.TestFilter) ... ok
test_simple (test.test_fps.TestPytorchClusterFPS) ... Segmentation fault (core dumped)
```

Any idea? cuda 10.1 pytorch 1.4.0.
Many thanks!

**Comment by tchaton** [comment] 2020-06-04 07:54
Hey @loicland,

I guess this one can be ignored for now as you still train most of models.
TestPytorchClusterFPS sometimes doesn't compile properly fps, resulting either in segmentation fault or random values.

@nicolas-chaulet, What do you think ?

**Comment by nicolas-chaulet** [comment] 2020-06-04 08:20
Yes this is the fps test for making sure that torch_cluster (part of pytorch geometric) works fine. Looks like it does not in your case... Could you try to comment that test out and run the tests again? Also, would you be able to run that test in an isolated environment with torch_cluster only? If it fails again then we know something is up with torch cluster.  I am asking because I haven't been able to reproduce on my machines... It is an odd one

**Comment by nicolas-chaulet** [comment] 2020-06-21 07:45
Closing for now. Looks like it is a problem with $PATH and $CPATH variables being alterred. Adding to troubleshooting

**Closed by nicolas-chaulet** 2020-06-21 07:45 UTC

**Comment by loicland** [comment] 2020-06-29 16:43
I was able to fix this bug by doing a few things (I am not sure which are necessary):
- using a venv instead of poetry
- making sure the CPATH was correctly set (to `path/to/cuda/include`)
- compiling torch-points-kernels from the cloned repo with `pip install -e .`
